auditbeat.modules:

- module: auditd
  audit_rules: |
    -w /etc/passwd -p wa -k identity
    -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access
    -a always,exit -S execve,execveat

- module: file_integrity
  paths:
    - /bin
    - /usr/bin
    - /sbin
    - /usr/sbin
    - /etc

- module: system
  datasets:
    - host
    - login
    - package
    - process
    - socket
    - user
  period: 30s
  state.period: 12h
  socket.include_localhost: false
  user.detect_password_changes: true

processors:
  - add_docker_metadata: ~


http.enabled: true
http.host: 0.0.0.0
monitoring.enabled: false
setup.template.overwrite: true
setup.kibana.host: "https://kibana:5601/kibana"
setup.kibana.ssl.enabled: true
setup.kibana.ssl.certificate_authorities: "/usr/share/certificates/ca/ca.crt"
setup.kibana.ssl.certificate: "/usr/share/certificates/kibana/kibana.crt"
setup.kibana.ssl.key: "/usr/share/certificates/kibana/kibana.key"
setup.ilm.enabled: true
setup.ilm.policy_name: "ILM"
setup.ilm.policy_file: "/usr/share/auditbeat/ilm.json"
setup.ilm_pattern: "{now/d}-000001"
setup.ilm_rollover_alias: "%{[@metadata][beat]}-%{[@metadata][version]}"
setup.dashboards.enabled: true
setup.template.settings:
  index:
    refresh_interval: 30s
    mapping:
      total_fields:
        limit: 8192

processors:
  - drop_event:
      when:
        equals:
           process.executable: "/usr/share/metricbeat/metricbeat"



output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "changeme"
  ssl.certificate_authorities: "/usr/share/certificates/ca/ca.crt"
  ssl.certificate: "/usr/share/certificates/auditbeat/auditbeat.crt"
  ssl.key: "/usr/share/certificates/auditbeat/auditbeat.key"

