---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

#title: "S1EM Dashboard"
subtitle: "S1EM"
logo: "https://user-images.githubusercontent.com/18678787/119020235-49428680-b99e-11eb-8621-935a62b966e1.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/V1D1AN/S1EM"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.
columns: 5
# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/V1D1AN/S1EM"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://github.com/V1D1AN/S1EM/wiki"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "CTI"
    icon: "fas fa-globe"
    items:
      - name: "Misp"
        logo: "/assets/icons/misp.png"
        tag: "app"
        url: "https://s1em_hostname/misp"
        target: "_blank" # optional html a tag target attribute
      - name: "Opencti"
        logo: "/assets/icons/opencti.png"
        tag: "app"
        url: "https://s1em_hostname/opencti"
        target: "_blank" # optional html a tag target attribute

  - name: "SIEM"
    icon: "fas fa-desktop"
    items:
      - name: "Elastic SIEM"
        logo: "/assets/icons/kibana-security.png"
        tag: "app"
        url: "https://s1em_hostname/kibana/app/security/overview"
        target: "_blank" # optional html a tag target attribute
      - name: "Monitoring"
        logo: "/assets/icons/kibana.png"
        tag: "app"
        url: "https://s1em_hostname/kibana/app/uptime"
        target: "_blank" # optional html a tag target attribute


  - name: "SOAR"
    icon: "fas fa-project-diagram"
    items:
      - name: "n8n"
        logo: "/assets/icons/n8n.png"
        tag: "app"
        url: "https://s1em_hostname/n8n/signin"
        target: "_blank" # optional html a tag target attribute


  - name: "MALWARE"
    icon: "fas fa-radiation"
    items:
      - name: "Mwdb"
        logo: "/assets/icons/mwdb.png"
        tag: "app"
        url: "http://s1em_hostname:8080"
        target: "_blank" # optional html a tag target attribute

  - name: "OSINT"
    icon: "fas fa-fingerprint"
    items:
      - name: "Spiderfoot"
        logo: "/assets/icons/spiderfoot.png"
        tag: "app"
        url: "https://s1em_hostname/spiderfoot/"
        target: "_blank" # optional html a tag target attribute

  - name: "FPC"
    icon: "fas fa-save"
    items:
      - name: "Arkime"
        logo: "/assets/icons/arkime.png"
        tag: "app"
        url: "https://s1em_hostname/arkime/"
        target: "_blank" # optional html a tag target attribute
     
  - name: "MITRE"
    icon: "fas fa-cogs"
    items:
      - name: "Elastic Rules"
        logo: "/assets/icons/attck.png"
        tag: "site"
        tagstyle: "is-success"
        url: "https://ela.st/detection-rules-navigator"
        target: "_blank" # optional html a tag target attribute


  - name: "SIRP"
    icon: "fas fa-sitemap"
    items:
      - name: "Velociraptor"
        logo: "/assets/icons/velociraptor.png"
        tag: "app"
        url: "https://s1em_hostname/velociraptor/"
        target: "_blank" # optional html a tag target attribute
      - name: "Zircolite"
        logo: "/assets/icons/zircolite.png"
        tag: "app"
        url: "https://s1em_hostname/kibana/app/dashboards#/view/832a98e0-9ef0-11ed-bedc-f9813e7df557"
        target: "_blank" # optional html a tag target attribute
      - name: "TheHive"
        logo: "/assets/icons/thehive.png"
        tag: "app"
        url: "https://s1em_hostname/thehive"
        target: "_blank" # optional html a tag target attribute
      - name: "Cortex"
        logo: "/assets/icons/cortex.png"
        tag: "app"
        url: "https://s1em_hostname/cortex"
        target: "_blank" # optional html a tag target attribute

  - name: "TOOLS"
    icon: "fas fa-tools"
    items:
      - name: "CyberChef"
        logo: "/assets/icons/cyberchef.jpg"
        tag: "app"
        url: "https://s1em_hostname/cyberchef/"
        target: "_blank" # optional html a tag target attribute
      - name: "CodiMD"
        logo: "/assets/icons/codimd.jpg"
        tag: "app"
        url: "https://s1em_hostname/codimd/"
        target: "_blank" # optional html a tag target attribute
      - name: "StartMe"
        logo: "/assets/icons/startme.png"
        tag: "site"
        tagstyle: "is-success"
        url: "https://start.me/p/6r66da/cybersecurity"
        target: "_blank" # optional html a tag target attribute

  - name: "UPLOAD"
    icon: "fas fa-cloud-arrow-up"
    items:
      - name: "PCAP"
        logo: "/assets/icons/pcap.png"
        tag: "app"
        url: "https://s1em_hostname/upload/"
        target: "_blank" # optional html a tag target attribute
      - name: "Zircolite"
        logo: "/assets/icons/evtx.png"
        tag: "app"
        url: "https://s1em_hostname/zircolite/"
        target: "_blank" # optional html a tag target attribute
      - name: "Velociraptor"
        logo: "/assets/icons/zip.png"
        tag: "app"
        url: "https://s1em_hostname/velociraptor-upload/"
        target: "_blank" # optional html a tag target attribute
