---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

#title: "S1EM Dashboard"
subtitle: "S1EM"
logo: "https://user-images.githubusercontent.com/18678787/119020235-49428680-b99e-11eb-8621-935a62b966e1.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/V1D1AN/S1EM"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.
columns: 5
# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/V1D1AN/S1EM"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://github.com/V1D1AN/S1EM/wiki"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "CTI"
    icon: "fas fa-globe"
    items:
      - name: "Misp"
        logo: "https://www.misp-project.org/img/logo.png"
        tag: "app"
        url: "https://s1em_hostname/misp"
        target: "_blank" # optional html a tag target attribute
      - name: "Opencti"
        logo: "https://www.opencti.io/wp-content/uploads/2022/03/logo_menu.png"
        tag: "app"
        url: "https://s1em_hostname/opencti"
        target: "_blank" # optional html a tag target attribute

  - name: "SIEM"
    icon: "fas fa-desktop"
    items:
      - name: "Elastic SIEM"
        logo: "https://elastic-content-share.eu/wp-content/uploads/edd/2020/06/security-logo-color-150x150.png"
        tag: "app"
        url: "https://s1em_hostname/kibana/app/security/overview"
        target: "_blank" # optional html a tag target attribute
      - name: "Monitoring"
        logo: "https://cdn.freebiesupply.com/logos/thumbs/2x/elastic-kibana-logo.png"
        tag: "app"
        url: "https://s1em_hostname/kibana/app/uptime"
        target: "_blank" # optional html a tag target attribute


  - name: "SOAR"
    icon: "fas fa-project-diagram"
    items:
      - name: "N8n"
        logo: "https://raw.githubusercontent.com/n8n-io/n8n/master/assets/n8n-logo.png"
        tag: "app"
        url: "https://s1em_hostname/n8n/"
        target: "_blank" # optional html a tag target attribute


  - name: "MALWARE"
    icon: "fas fa-radiation"
    items:
      - name: "Mwdb"
        logo: "http://s1em_hostname:8080/static/media/logo.787cfdb1.png"
        tag: "app"
        url: "http://s1em_hostname:8080"
        target: "_blank" # optional html a tag target attribute

  - name: "OSINT"
    icon: "fas fa-fingerprint"
    items:
      - name: "Spiderfoot"
        logo: "https://www.spiderfoot.net/wp-content/themes/spiderfoot/img/logo.svg"
        tag: "app"
        url: "https://s1em_hostname/spiderfoot/"
        target: "_blank" # optional html a tag target attribute

  - name: "FPC"
    icon: "fas fa-save"
    items:
      - name: "Arkime"
        logo: "https://avatars.githubusercontent.com/u/71138764?s=200&v=4"
        tag: "app"
        url: "https://s1em_hostname/arkime/"
        target: "_blank" # optional html a tag target attribute

  - name: "CVE"
    icon: "fas fa-bug"
    items:
      - name: "Cvetrends"
        logo: "https://cve.mitre.org/images/cvelogobanner.png"
        tag: "site"
        tagstyle: "is-success"
        url: "https://cvetrends.com/"
        target: "_blank" # optional html a tag target attribute

  - name: "SIRP"
    icon: "fas fa-sitemap"
    items:
      - name: "TheHive"
        logo: "https://github.com/TheHive-Project/TheHive/raw/main/images/thehive-logo.png"
        tag: "app"
        url: "https://s1em_hostname/thehive"
        target: "_blank" # optional html a tag target attribute
      - name: "Cortex"
        logo: "https://github.com/TheHive-Project/Cortex/raw/master/images/cortex-logo.png"
        tag: "app"
        url: "https://s1em_hostname/cortex"
        target: "_blank" # optional html a tag target attribute

  - name: "TOOLS"
    icon: "fas fa-tools"
    items:
      - name: "CyberChef"
        logo: "https://www.gchq.gov.uk/images/CyberChef768x512.jpg"
        tag: "app"
        url: "https://s1em_hostname/cyberchef/"
        target: "_blank" # optional html a tag target attribute
      - name: "CodiMD"
        logo: "https://cdn.futura-sciences.com/buildsv6/images/wide1920/4/b/e/4be0f23a59_122541_markdown.jpg"
        tag: "app"
        url: "https://s1em_hostname/codimd/"
        target: "_blank" # optional html a tag target attribute
      - name: "Upload"
        logo: "https://fileproinfo.com/images/pcap_file_extension.png"
        tag: "app"
        url: "https://s1em_hostname/upload/"
        target: "_blank" # optional html a tag target attribute
      - name: "StartMe"
        logo: "https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/v1477931274/aq1yfkwbl5yslbedhkyj.png"
        tag: "site"
        tagstyle: "is-success"
        url: "https://start.me/p/6r66da/cybersecurity"
        target: "_blank" # optional html a tag target attribute
